use utoipa::OpenApi;

use crate::api::error::{ApiError, ApiErrorBody};
use crate::api::handlers;
use crate::api::handlers::orgs::{
    CheckSlugResponse, CreateOrgRequest, MemberView as OrgMemberView, OrgView,
    SwitchActiveOrgRequest, UpdateMemberRoleRequest, UpdateOrgRequest,
};
use crate::api::page::PageEnvelope;
use crate::api::public_error::{PublicApiError, PublicApiErrorBody};
use crate::api::types::{
    BulkAction, BulkActionFailure, BulkActionRequest, BulkActionResponse, DashboardSummary,
    FlowStepBucket, FlowStepSeries, FlowStepTrend, Last24hSummary, LatencyBucket, LatencySeries,
    LatencySeriesByRegion, RegionLatencySeries, StatusBreakdown, SystemSummary, TagCount,
    TargetsSummary, TestRequest, TestResponse,
};
use crate::domain::Role;
use crate::domain::{
    ActorType, AlertBinding, ChannelConfig, ChannelKind, CheckResult, CheckSpec, CheckStatus,
    ComponentHistoryResponse, DayState, DnsCheck, DnsRecordType, DomainExpiryCheck,
    EscalationPolicy, EscalationPolicySummary, EscalationStep, EscalationTarget,
    EscalationTargetType, ExpectedStatus, FlowCheck, FlowStep, HeartbeatCheck, HttpCheck,
    HttpMethod, Incident, IncidentEvent, IncidentEventKind, IncidentNarrationUpdate,
    IncidentOrigin, IncidentSeverity, IncidentState, IncidentStatusPhase, IncidentUrgency,
    IncidentVisibility, MaintenanceFilter, MaintenanceWindow, MaintenanceWindowUpdate,
    NewEscalationPolicy, NewEscalationStep, NewEscalationTarget, NewIncidentUpdate,
    NewMaintenanceWindow, NewManualIncident, NewNotificationChannel, NewOnCallLayer,
    NewOnCallOverride, NewOnCallParticipant, NewOnCallSchedule, NewTarget, NotificationChannel,
    NotificationChannelUpdate, OnCallLayer, OnCallOverride, OnCallParticipant, OnCallSchedule,
    OnCallScheduleDetail, OnCallScheduleSummary, OpsIncident, OverallState, OverallStatus,
    PingCheck, PublicActionItem, PublicComponent, PublicComponentGroup, PublicComponentStatus,
    PublicIncident, PublicIncidentUpdate, PublicMaintenance, PublicMaintenanceList,
    PublicPostmortem, PublicStatusPage, RotationType, Target, TargetAlerts, TargetUpdate, TcpCheck,
    TlsCertCheck, WriteSource,
};
use crate::storage::UptimeStats;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "uptimepage",
        description = "HTTP / TCP / ping / heartbeat / TLS-cert / domain-expiry / DNS / browser-flow health-check service. \
                       Schedules checks against configured targets, stores results, \
                       exposes a REST API.",
        license(name = "MIT"),
    ),
    servers((url = "/", description = "Current host")),
    paths(
        handlers::health::healthz,
        handlers::health::readyz,
        handlers::targets::create,
        handlers::targets::bulk_create,
        handlers::targets::list,
        handlers::targets::get,
        handlers::targets::update,
        handlers::targets::get_target_regions,
        handlers::targets::set_target_regions,
        handlers::targets::list_regions,
        handlers::targets::delete,
        handlers::targets::bulk_action,
        handlers::targets::test_check,
        handlers::targets::check_now,
        handlers::targets::get_heartbeat,
        handlers::targets::rotate_heartbeat,
        handlers::targets::revoke_heartbeat_previous,
        handlers::results::list_results,
        handlers::results::latency,
        handlers::results::latency_by_region,
        handlers::results::flow_steps,
        handlers::results::uptime,
        handlers::results::list_incidents,
        handlers::tags::list_tags,
        handlers::dashboard::dashboard_summary,
        handlers::public::public_status,
        handlers::public::component_history,
        handlers::public::public_incidents,
        handlers::public::public_incident,
        handlers::public::public_incidents_rss,
        handlers::public::public_maintenance,
        handlers::public::public_badge,
        handlers::maintenance::create_maintenance,
        handlers::maintenance::list_maintenance,
        handlers::maintenance::get_maintenance,
        handlers::maintenance::update_maintenance,
        handlers::maintenance::delete_maintenance,
        handlers::variables::list,
        handlers::variables::get,
        handlers::variables::create,
        handlers::variables::update,
        handlers::variables::delete,
        handlers::notification_channels::create,
        handlers::notification_channels::list,
        handlers::notification_channels::get,
        handlers::notification_channels::update,
        handlers::notification_channels::delete,
        handlers::notification_channels::test_send,
        handlers::notification_channels::test_config,
        handlers::notification_channels::resend_verification,
        handlers::notification_channels::telegram_link_mint,
        handlers::notification_channels::telegram_link_status,
        handlers::notification_channels::whatsapp_link_mint,
        handlers::notification_channels::whatsapp_link_status,
        handlers::notification_channels::delegate_link_mint,
        handlers::notification_channels::delegate_link_list,
        handlers::notification_channels::delegate_link_revoke,
        handlers::incidents::update_incident_narration,
        handlers::incidents::post_incident_update,
        handlers::incidents::list_incidents,
        handlers::incidents::get_incident,
        handlers::incidents::incident_notifications,
        handlers::incidents::declare_incident,
        handlers::incidents::acknowledge_incident,
        handlers::incidents::resolve_incident,
        handlers::incidents::reopen_incident,
        handlers::incidents::assign_incident,
        handlers::incidents::add_incident_note,
        handlers::incidents::publish_incident,
        handlers::incidents::unpublish_incident,
        handlers::incidents::incident_metrics,
        handlers::incidents::get_postmortem,
        handlers::incidents::put_postmortem,
        handlers::incidents::publish_postmortem,
        handlers::incidents::unpublish_postmortem,
        handlers::escalation_policies::list,
        handlers::escalation_policies::create,
        handlers::escalation_policies::get,
        handlers::escalation_policies::replace,
        handlers::escalation_policies::delete,
        handlers::escalation_policies::get_org_default,
        handlers::escalation_policies::set_org_default,
        handlers::escalation_policies::get_target_policy,
        handlers::escalation_policies::set_target_policy,
        handlers::on_call::list,
        handlers::on_call::create,
        handlers::on_call::get,
        handlers::on_call::replace,
        handlers::on_call::delete,
        handlers::on_call::add_override,
        handlers::on_call::delete_override,
        handlers::on_call::who,
        handlers::on_call::get_my_contacts,
        handlers::on_call::set_my_contacts,
        handlers::orgs::create_org,
        handlers::orgs::list_my_orgs,
        handlers::orgs::list_my_deleted_orgs,
        handlers::orgs::get_org,
        handlers::orgs::update_org,
        handlers::orgs::delete_org,
        handlers::orgs::restore_org,
        handlers::orgs::check_slug,
        handlers::orgs::list_org_members,
        handlers::orgs::remove_org_member,
        handlers::orgs::update_org_member_role,
        handlers::orgs::switch_active_org,
        handlers::usage::get_org_usage,
        handlers::holds::list_holds,
        handlers::holds::set_holds,
        handlers::usage::get_me_usage,
        handlers::status_page::list_pages,
        handlers::status_page::create_page,
        handlers::status_page::get_page,
        handlers::status_page::update_page,
        handlers::status_page::delete_page,
        handlers::status_page::list_components,
        handlers::status_page::add_component,
        handlers::status_page::update_component,
        handlers::status_page::remove_component,
        handlers::status_page::remove_subscriber,
        handlers::status_page::reorder_components,
        handlers::status_page::upload_logo,
        handlers::status_page::delete_logo,
        handlers::shares::create_share,
        handlers::shares::list_shares,
        handlers::shares::revoke_share,
        handlers::account::data_export,
        handlers::account::delete_account,
        handlers::account::restore_account,
        handlers::identities::unlink,
        handlers::api_tokens::list,
        handlers::api_tokens::create,
        handlers::api_tokens::rename,
        handlers::api_tokens::revoke,
    ),
    components(
        schemas(
            ApiError,
            ApiErrorBody,
            handlers::health::HealthResponse,
            handlers::health::ReadinessResponse,
            handlers::health::DependencyState,
            Target,
            NewTarget,
            TargetUpdate,
            CheckSpec,
            HttpCheck,
            TcpCheck,
            PingCheck,
            HeartbeatCheck,
            handlers::targets::HeartbeatInfo,
            handlers::targets::RotateHeartbeatRequest,
            TlsCertCheck,
            DomainExpiryCheck,
            DnsCheck,
            DnsRecordType,
            FlowCheck,
            FlowStep,
            HttpMethod,
            ExpectedStatus,
            CheckResult,
            CheckStatus,
            WriteSource,
            UptimeStats,
            LatencyBucket,
            LatencySeries,
            LatencySeriesByRegion,
            RegionLatencySeries,
            FlowStepSeries,
            FlowStepTrend,
            FlowStepBucket,
            Incident,
            AlertBinding,
            TargetAlerts,
            crate::domain::RegionIncidentPolicy,
            handlers::targets::TargetRegions,
            handlers::targets::RegionInfo,
            handlers::targets::RegionCatalog,
            TagCount,
            DashboardSummary,
            TargetsSummary,
            StatusBreakdown,
            Last24hSummary,
            SystemSummary,
            BulkActionRequest,
            BulkAction,
            BulkActionResponse,
            BulkActionFailure,
            TestRequest,
            TestResponse,
            PageEnvelope<Target>,
            PageEnvelope<CheckResult>,
            PageEnvelope<Incident>,
            PageEnvelope<TagCount>,
            PublicApiError,
            PublicApiErrorBody,
            PublicStatusPage,
            OverallStatus,
            OverallState,
            PublicComponentGroup,
            PublicComponent,
            PublicComponentStatus,
            DayState,
            PublicIncident,
            PublicIncidentUpdate,
            PublicPostmortem,
            PublicActionItem,
            IncidentSeverity,
            IncidentStatusPhase,
            PublicMaintenance,
            PublicMaintenanceList,
            ComponentHistoryResponse,
            PageEnvelope<PublicIncident>,
            NewMaintenanceWindow,
            MaintenanceWindowUpdate,
            MaintenanceWindow,
            MaintenanceFilter,
            PageEnvelope<MaintenanceWindow>,
            crate::domain::Variable,
            crate::domain::NewVariable,
            handlers::variables::VariableView,
            handlers::variables::VariableValueUpdate,
            NotificationChannel,
            NewNotificationChannel,
            NotificationChannelUpdate,
            ChannelConfig,
            ChannelKind,
            handlers::notification_channels::TestNotificationResponse,
            handlers::notification_channels::TestChannelConfigRequest,
            handlers::notification_channels::OneTapLinkRequest,
            handlers::notification_channels::TelegramLinkResponse,
            handlers::notification_channels::DelegateLinkRequest,
            handlers::notification_channels::DelegateLinkResponse,
            handlers::notification_channels::DelegateLinkRow,
            handlers::notification_channels::OneTapLinkStatusResponse,
            IncidentNarrationUpdate,
            NewIncidentUpdate,
            OpsIncident,
            IncidentEvent,
            IncidentEventKind,
            ActorType,
            IncidentState,
            IncidentUrgency,
            IncidentOrigin,
            IncidentVisibility,
            NewManualIncident,
            handlers::incidents::IncidentDetail,
            handlers::incidents::LifecycleBody,
            handlers::incidents::AssignBody,
            handlers::incidents::NoteBody,
            handlers::incidents::PublishBody,
            crate::domain::IncidentMetrics,
            crate::domain::MetricBucket,
            crate::domain::MonitorIncidentCount,
            crate::domain::IncidentPostmortem,
            crate::domain::PostmortemUpsert,
            crate::domain::ActionItem,
            EscalationPolicy,
            EscalationPolicySummary,
            EscalationStep,
            EscalationTarget,
            EscalationTargetType,
            NewEscalationPolicy,
            NewEscalationStep,
            NewEscalationTarget,
            handlers::escalation_policies::PolicyBinding,
            OnCallSchedule,
            OnCallScheduleSummary,
            OnCallScheduleDetail,
            OnCallLayer,
            OnCallParticipant,
            OnCallOverride,
            RotationType,
            NewOnCallSchedule,
            NewOnCallLayer,
            NewOnCallParticipant,
            NewOnCallOverride,
            handlers::on_call::WhoResponse,
            handlers::on_call::ContactChannels,
            CreateOrgRequest,
            UpdateOrgRequest,
            OrgView,
            OrgMemberView,
            CheckSlugResponse,
            SwitchActiveOrgRequest,
            UpdateMemberRoleRequest,
            handlers::usage::QuotaUsage,
            handlers::usage::PlanSummary,
            handlers::usage::OrgQuotas,
            handlers::usage::UsagePolicy,
            handlers::usage::UsageRateLimits,
            handlers::usage::UsageFeatures,
            handlers::usage::OrgUsageResponse,
            handlers::usage::MeUsageResponse,
            crate::domain::MonitorShare,
            crate::domain::NewMonitorShare,
            handlers::status_page::StatusPageView,
            handlers::status_page::CreatePageRequest,
            handlers::status_page::UpdatePageRequest,
            handlers::status_page::BrandingInput,
            handlers::status_page::ReorderRequest,
            handlers::status_page::LogoResponse,
            crate::domain::StatusPageComponent,
            crate::domain::NewStatusPageComponent,
            crate::domain::StatusPageComponentUpdate,
            crate::domain::StatusPageId,
            crate::domain::PublicOrgBranding,
            Role,
            crate::storage::postgres_secrets::RedactedTarget,
            handlers::account::UserDataExport,
            handlers::account::UserExport,
            handlers::account::OAuthIdentityExport,
            handlers::account::SessionMetadata,
            handlers::account::ApiTokenMetadata,
            handlers::account::OwnedOrgExport,
            handlers::account::OrgExport,
            handlers::account::IncidentExport,
            handlers::account::MaintenanceExport,
            handlers::account::StatusPageExport,
            handlers::account::StatusPageComponentExport,
            handlers::account::MemberMetadata,
            handlers::account::MembershipExport,
            handlers::account::LoginAttemptExport,
            handlers::account::CredentialEventExport,
            handlers::account::AuditEntryExport,
            handlers::account::McpAuditExport,
            handlers::account::DeletionConfirmation,
            crate::auth::OauthProvider,
            handlers::api_tokens::NewApiTokenRequest,
            handlers::api_tokens::NewApiTokenResponse,
            handlers::api_tokens::ApiTokenView,
            handlers::api_tokens::RenameApiTokenRequest,
        ),
    ),
    tags(
        (name = "health",        description = "Liveness and readiness probes"),
        (name = "targets",       description = "Target CRUD and operations"),
        (name = "results",       description = "Check results, uptime, incidents"),
        (name = "tags",          description = "Tag inventory"),
        (name = "dashboard",     description = "Fleet-wide aggregated views"),
        (name = "public_status", description = "Public, unauthenticated status page surface"),
        (name = "maintenance",   description = "Scheduled maintenance windows (operator)"),
        (name = "notification-channels", description = "Notification delivery destinations (operator)"),
        (name = "incidents",     description = "Incident narration and timeline (operator)"),
        (name = "escalation",    description = "Escalation policies + monitor/org bindings (owner)"),
        (name = "on-call",       description = "On-call schedules, overrides, and contact channels"),
        (name = "orgs",          description = "Organisation management and membership"),
        (name = "status-pages",  description = "Public status page management (per-org, owner-managed)"),
        (name = "shares",        description = "Read-only single-monitor share links (member-managed)"),
        (name = "account",       description = "GDPR data export and account deletion"),
        (name = "api-tokens",    description = "Personal API token management (browser session only)"),
    ),
)]
pub struct ApiDoc;

/// The document, built once: served at `/api/openapi.json` and read by the
/// request-body check.
pub fn openapi() -> &'static utoipa::openapi::OpenApi {
    static DOC: std::sync::LazyLock<utoipa::openapi::OpenApi> =
        std::sync::LazyLock::new(ApiDoc::openapi);
    &DOC
}
